baseURL = "http://knuxbbs.com/"
languageCode = "pt-br"
title = "açúcares sintáticos"
theme = "hikari"

[permalinks]
	post = "/:year/:month/:day/:slug"

[params]
	name = "Bruno Bacelar"
	description = "A blog about programming and technology in general."
	copyright = "Site feito com [HUGO](//gohugo.io) - Tema: [HIKARI](//github.com/digitalcraftsman/hugo-hikari-theme) - Conteúdo licenciado sob [CC BY-SA 3.0](//creativecommons.org/licenses/by-sa/3.0/)"

	# Custom assets can be linked with their paths relative to static/
	custom_css = []
	custom_js  = []

	# Links to newer/older blog posts
	newer = "Mais recente"
	older = "Mais antigo"

	pageNotFoundTitle = "404"
	pageNotFoundSubtitle = "Desculpa, mas a página solicitada <br> não foi encontrada."

[params.offcanvas]
	# Menu items
	title = "Oi, eu sou o Bruno"
	bio = "E este é um blog para falar principalmente sobre assuntos técnicos."
	subscribe = "Inscreva-se"
	followme = "Sigam-me os bons"

	# Enable Google search
	search_enabled = false
	search = "Search"

	[[params.offcanvas.socialnetworks]]
		name = "Twitter"
		url = "//twitter.com/knuxbbs"

	[[params.offcanvas.socialnetworks]]
		name = "Github"
		url = "//github.com/knuxbbs"